### ISSUE TITLE
`Uncaught TypeError: m.trim is not a function` in Storybook v7.1

### ISSUE THREAD

**Issue by maddesigns** [whitespace-se/storybook-addon-html#104]
I’m using your fantastic addon successfully with Storybook 7 Angular, but on Storybook 7.1 (beta) I’m getting following errors:

```
Uncaught TypeError: m.trim is not a function
    Ch http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:59
    renderWithHooks http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    updateFunctionComponent http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    beginWork http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:71
    callCallback2 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:2
    invokeGuardedCallbackDev http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:2
    invokeGuardedCallback http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:2
    beginWork$1 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    performUnitOfWork http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    workLoopSync http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    performSyncWorkOnRoot http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    flushSyncCallbackQueueImpl http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    unstable_runWithPriority http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:1
    runWithPriority$1 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    flushSyncCallbackQueueImpl http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    flushSyncCallbackQueue http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    scheduleUpdateOnFiber http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    enqueueSetState http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:44
    setState http://0.0.0.0:6006/sb-manager/chunk-3FAXWWKG.js:3
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    newState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setAddonState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    useSharedState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    sP http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:93
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    Channel http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handler http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    PostMessageTransport http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    createBrowserChannel http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    ReactProvider http://0.0.0.0:6006/sb-manager/runtime.js:1
    <anonymous> http://0.0.0.0:6006/sb-manager/runtime.js:1
manager-bundle.js:59:848
```

and 

```
Uncaught (in promise) TypeError: can't access property "languages", a is undefined
    n http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:80
    wk http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:80
    ZW http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:80
    Wk http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:90
    yn http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:92
    Mi http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:92
    D http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:93
    updateMemo http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    useMemo http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    useMemo http://0.0.0.0:6006/sb-manager/chunk-3FAXWWKG.js:9
    sP http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:93
    Tabs http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:220
    Tabs http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:220
    renderWithHooks http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    updateFunctionComponent http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:69
    beginWork http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:71
    beginWork$1 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    performUnitOfWork http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    workLoopSync http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    performSyncWorkOnRoot http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    flushSyncCallbackQueueImpl http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    unstable_runWithPriority http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:1
    runWithPriority$1 http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    flushSyncCallbackQueueImpl http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    flushSyncCallbackQueue http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:9
    scheduleUpdateOnFiber http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:90
    enqueueSetState http://0.0.0.0:6006/sb-manager/chunk-BOQB7P2G.js:44
    setState http://0.0.0.0:6006/sb-manager/chunk-3FAXWWKG.js:3
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    newState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setAddonState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    setState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    useSharedState http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:53
    sP http://0.0.0.0:6006/sb-addons/whitespace-html-esm-preset-12/manager-bundle.js:93
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    Channel http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handler http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    handleEvent http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    PostMessageTransport http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    createBrowserChannel http://0.0.0.0:6006/sb-manager/chunk-SU7DKTZC.js:39
    ReactProvider http://0.0.0.0:6006/sb-manager/runtime.js:1
    <anonymous> http://0.0.0.0:6006/sb-manager/runtime.js:1
2 manager-bundle.js:80:692

```

Maybe it’s dependencies related, but I can’t find out atm what to do.

**Comment by dgonzalezr** [comment]
@maddesigns can you verify if you're using Prettier and which version do you have? **Asking because I got the same when upgrading to Prettier v3.0.0**, downgrading to Prettier v2.8.8 fixed it for me.

**Comment by maddesigns** [comment]
Confirmed @dgonzalezr. Works with Prettier v2.8.8 and Storybook 7.1 release.

**Comment by kevintyj** [comment]
I would really love to use this add-on but because of incompatibility with Prettier v3, we are unable to use it :(
Any word from the maintainers if the Prettier version is planned for an update?
Our team relies on some of the new features such as foreign language commenting styling and such for our team to maintain our pretty ✨ code. 
Awesome work from the team at @whitespace-dev! Thank you for the amazing addon.

**Comment by oxilor** [comment]
I have the same problem. I'm using storybook `7.2.1`. Upgrading the prettier from `2.8.8` to `3` leads to the following error:
```tsx
Uncaught (in promise) TypeError: g.trim is not a function
    at Eh (SyntaxHighlighter.js:91:22)
    at renderWithHooks (chunk-SJD7EFYL.js:69:936)
    at updateFunctionComponent (chunk-SJD7EFYL.js:69:48263)
    at beginWork (chunk-SJD7EFYL.js:71:21338)
    at HTMLUnknownElement.callCallback2 (chunk-SJD7EFYL.js:2:1918)
    at Object.invokeGuardedCallbackDev (chunk-SJD7EFYL.js:2:2442)
    at invokeGuardedCallback (chunk-SJD7EFYL.js:2:3700)
    at beginWork$1 (chunk-SJD7EFYL.js:90:39484)
    at performUnitOfWork (chunk-SJD7EFYL.js:90:21018)
    at workLoopSync (chunk-SJD7EFYL.js:90:20642)
```
If I remove `@whitespace/storybook-addon-html` there are no errors.

**Comment by methodev** [comment]
Downgrading to 2.8.8 doesn't always work because when I delete the /node_modules/.cache dir, Storybook is unabled to run and crashes with the following error:
`prettier.resolveConfig.sync is not a function`

Looking forward to this getting a fix asap. 🙂

**Comment by mikeriley131** [comment]
For anyone running into this issue, I found another plugin that seems to work just the same that does not have the same conflicts with Prettier v3.

https://storybook.js.org/addons/@un-known/storybook-addon-html
